### ISSUE TITLE
Failure in prediction

### ISSUE THREAD

**Issue by muschellij2** [jasonccai/HeadCTSegmentation#1]
```bash
git clone --depth=1 https://github.com/jasonccai/HeadCTSegmentation
#Cloning into 'HeadCTSegmentation'...
#remote: Enumerating objects: 33, done.
#remote: Counting objects: 100% (33/33), done.
#remote: Compressing objects: 100% (32/32), done.
#remote: Total 33 (delta 0), reused 10 (delta 0), pack-reused 0
#Unpacking objects: 100% (33/33), 58.01 MiB | 2.48 MiB/s, done.
cd HeadCTSegmentation/
cp ~/Downloads/NPH_weights.hdf5 weights.hdf5     
z_controlboard.py 
# To use this model, please download its weights and unzip the hdf5 file into '/Users/johnmuschelli/Desktop/HeadCTSegmentation'.
# Place the volumes to be segmented into the 'image_data_predict' folder. All volumes should measure 512*512 voxels axially.
# The model will write its predictions into 'results_folder' with a corresponding timestamp.
# Press enter to start or 'Ctrl+C' to exit: 
# 2020-10-07 18:10:54.881013: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
# To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
# 2020-10-07 18:10:54.893505: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fcc10b514e0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
# 2020-10-07 18:10:54.893533: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
# Traceback (most recent call last):
#   File "z_controlboard.py", line 120, in <module>
#     model.load_weights(weights)
#   File "/Users/johnmuschelli/Library/Python/3.7/lib/python/site-packages/tensorflow/python/keras/engine/training.py", line 2211, in load_weights
#     hdf5_format.load_weights_from_hdf5_group(f, self.layers)
#   File "/Users/johnmuschelli/Library/Python/3.7/lib/python/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 708, in load_weights_from_hdf5_group
#     K.batch_set_value(weight_value_tuples)
#   File "/Users/johnmuschelli/Library/Python/3.7/lib/python/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
#     return target(*args, **kwargs)
#   File "/Users/johnmuschelli/Library/Python/3.7/lib/python/site-packages/tensorflow/python/keras/backend.py", line 3576, in batch_set_value
#     x.assign(np.asarray(value, dtype=dtype(x)))
#   File "/Users/johnmuschelli/Library/Python/3.7/lib/python/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 858, in assign
#     self._shape.assert_is_compatible_with(value_tensor.shape)
#   File "/Users/johnmuschelli/Library/Python/3.7/lib/python/site-packages/tensorflow/python/framework/tensor_shape.py", line 1134, in assert_is_compatible_with
#     raise ValueError("Shapes %s and %s are incompatible" % (self, other))
# ValueError: Shapes (1, 1, 64, 12) and (17, 64, 1, 1) are incompatible
```

**Comment by muschellij2** [comment]
I'm pretty sure https://github.com/jasonccai/HeadCTSegmentation/blob/master/z_controlboard.py#L97 should be `nb_classes = 17`

**Comment by jasonccai** [comment]
Thank you! You're right.
We added a few more structures, and we'll update the file to reflect this.

**Comment by muschellij2** [comment]
BTW - I adapted the model into an R package here: https://github.com/muschellij2/ctseg
